version: "3.9"

services:
  api:
    build: .
    container_name: early_churn_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/churn_db

  db:
    image: postgres:15
    container_name: early_churn_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churn_db
    ports:
      - "5432:5432"
